"""empty message

Revision ID: 501ae278be6f
Revises: 
Create Date: 2024-09-20 17:42:39.585445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501ae278be6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restore_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.String(length=120), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('userPhoto', sa.String(length=250), nullable=True),
    sa.Column('petStar', sa.String(length=80), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('hobbies', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('forum_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forumTopicTittle', sa.String(length=80), nullable=False),
    sa.Column('forumTopicText', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postPhoto', sa.String(length=250), nullable=False),
    sa.Column('postText', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentPostText', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicResponseText', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('forumtopic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forumtopic_id'], ['forum_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_response')
    op.drop_table('comment_post')
    op.drop_table('post')
    op.drop_table('forum_topic')
    op.drop_table('user')
    op.drop_table('restore_password')
    # ### end Alembic commands ###
